inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - gemfiles/**/*
    - spec/dummy/**/*
    - vendor/**/*
    - app/models/think_feel_do_dashboard/reports/**/*
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

AbcSize:
  Max: 16

ClassLength:
  Enabled: false

Documentation:
  Exclude:
    - spec/**/*

DotPosition:
  Enabled: false

TrailingBlankLines:
  Enabled: false

HandleExceptions:
  Enabled: false

IfUnlessModifier:
  Enabled: false

LineLength:
  Exclude:
    - spec/**/*

MethodLength:
  Max: 15

StringLiterals:
  EnforcedStyle: double_quotes

Style/GuardClause:
  Enabled: false

WordArray:
  Enabled: false
